server:
  port: 8888

logging:
  path: logs
  file: dashanManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/course?serverTimezone=GMT
    username: root
    password: root

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*